services:
  qiu-pay:
    image: qiusheng26/qiu-pay:latest
    container_name: qiu-pay
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
